version: "3.8"
services:
  news_api:
    container_name: news_api
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    networks:
      - app_network

  nginx_server:
    container_name: nginx_server
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - news_api
    environment:
      NGINX_FPM_HOST: news_api
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
